### PR TITLE
Add datacenters.network

### PR DESCRIPTION
**Pull request by williamdes**
This is my list of IPs that attacked my mail services as a hosting provider

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @philwhineray
What do you think about my request, do I need so do some changes?

**Comment by philwhineray** [comment]
Hi, sorry for the lack of commentary. I haven't been involce with the ip lists side of things. @ktsaou can you confirm we are OK to merge this?

My only observation is the name is super-general (I understand that is also the case of the source of the list) so maybe mentioning mailserver attackers as part of the name would be good.

**Comment by williamdes** [comment]
> Hi, sorry for the lack of commentary. I haven't been involce with the ip lists side of things. @ktsaou can you confirm we are OK to merge this?
> 
> My only observation is the name is super-general (I understand that is also the case of the source of the list) so maybe mentioning mailserver attackers as part of the name would be good.

Hi @philwhineray 
Thank you for commenting, I applied your suggestion about the list name.
@ktsaou do you have some other comments before this can be merged ?

**Comment by williamdes** [comment]
Last 🏓 before I close my request

**Pull request closed without merging**
