### PR TITLE
explicitly logs BLOCKED or UNMATCHED when dropping packets

### PR DESCRIPTION
**Pull request by ktsaou**
In many cases, for auditing reasons we add log lines to verify connections have been established.

An easy way to do it, is by adding this at the top of firehol.conf:

```sh
   action AUDIT_ACCEPT \
        action ACCEPT state NEW log "AUDIT ACCEPT" \
        next action ACCEPT
```

So, we can later use `server xxx AUDIT_ACCEPT`.

In such cases, the indirectly dropped packets which are logged without any positive or negative indication, are often misinterpreted. 

This PR, adds `BLOCKED` or `UNMATCHED` to all such log lines, to make it clear that these logs have actually blocked traffic.

### CODE REVIEW

**Comment by philwhineray** [comment]
Relatedly, I found that the fix for #260 does not work properly in namespaces - the file checked does not get included. We would check `/proc/sys/net/netfilter/nf_conntrack_tcp_max_retrans` instead, which does appear inside namespaces.

**Comment by philwhineray** [comment]
Seems reasonable but I think you have stumbled over the very few automated tests I managed to include.

It should be simple enough to update them, provided you can run them locally -  use `unittest all` in the tests directory, then give the `update-audit` script in the the names of the conf files that fail.

If for some reason you cannot run the tests, let me know and I will grab your PR and send you a patch.

**Comment by philwhineray** [comment]
Oddly my comments above are out of order. Did Daylight Savings kick in for github today?

I recommend updating to the latest master which includes #280 which makes the tests slightly more robust in the face of minor changes to the output of userspace tools.

Then, if you agree to PR #279 then the tests will run much more quickly because they won't have a long timeout waiting for a netfilter file that will never appear.

My original offer still stands though, I can update the tests for you if you cannot get it to work easily.

**Comment by ktsaou** [comment]
Well, I merged the latest code, but I get this:

```
Missing module(s). Run:
  sudo modprobe iptable_filter
../sbin/install.config.in missing: run configure



Usage: ./unittest [-v] [--strace] all|test-dir|test-dir/test.conf [...]

Example use of strace: see all non-absolute path executions:
  grep 'execve[^,]*, \["[^/]' strace.*.txt | less
```

I have run configure.

**Comment by ktsaou** [comment]
@philwhineray I used the output of travis to understand what needs to be changed.
However, it seems that now travis never completes.
Please have a look.

**Comment by ktsaou** [comment]
ok I think I fixed them all

**Comment by ktsaou** [comment]
yeap it seems ok now. @philwhineray if you agree, please merge it.

**Comment by philwhineray** [comment]
Looks good to me #279 will sort out the delays in travis.

**Pull request merged**
