### PR TITLE
Fix FireQoS bugs

### LINKED ISSUE #248: FireQOS DSCP matching produces wrong tc command
I'm attempting to use DSCP matching in FireQOS 3.1.3. When I run debug mode to observe the `tc` commands, I see that FireQOS specifies the TOS value incorrectly.

For example, I have a class where I am doing `match dscp AF31`. The resulting `tc` command that FireQOS uses is: `tc filter add dev eth2 parent 1:0 protocol ip prio 30 u32 match ip tos 0x68 0x68 flowid 1:13`.

**In particular, it seems the _mask_ parameter given to `tc` is incorrect.** When I run FireQOS in status mode, I see that packets with AF33 are being matched by this class, which is wrong.

A TOS value is an 8-bit number, but only the first 6 bits are the DSCP value. So the _mask_ parameter given to `tc` should look at the first 6 bits and ignore the last 2 bits. Which **I guess should be `0xfc`**.

### LINKED ISSUE #249: FireQOS match tcp doesn't do anything
Using, FireQOS 3.1.3 when I configure a class that has `match tcp` or `match protocol tcp`, the resulting `tc filter` command is missing the appropriate match statement. According to FireQOS debug mode, the resulting `tc` command is `tc filter add dev eth0 parent 1:0 protocol ip prio 10 flowid 1:11`. **Shouldn't the `tc` command contain `match ip protocol 6` somewhere?**

### PR DESCRIPTION
**Pull request by ktsaou**
1. fixes #248 (wrong DSCP matches)
2. fixes #249 (no rule generated for TCP protocol match)

### CODE REVIEW

**Comment by ktsaou** [comment]
@mikenor I would appreciate it if you can test these changes and confirm they work for you.

**Comment by mikenor** [comment]
FireQOS `debug` action seems to be showing correct `tc` commands now. But I can't get the `status` action to work. It just says ERROR for all values, e.g.:
```
 Class Utilization on BLAH (eth0 output => eth0) - values in Kbit/s
  TOTAL     bgp realtim interac default 
  ERROR   ERROR   ERROR   ERROR   ERROR 
  ERROR   ERROR   ERROR   ERROR   ERROR 
  ERROR   ERROR   ERROR   ERROR   ERROR 
  ERROR   ERROR   ERROR   ERROR   ERROR 
  ERROR   ERROR   ERROR   ERROR   ERROR 
```
Error seems to occur no matter what I use for matches, so maybe unrelated to these fixes.

**Comment by mikenor** [comment]
I played around some more with trying to replicate the `status` problem. If I start FireQOS using the `start` action, then the `status` action works properly. If I start FireQOS using the `debug` action, then the `status` action gives ERROR for all values. So I guess it is unrelated. The TCP match and DSCP match are working correctly.

**Comment by ktsaou** [comment]
hm... I think in debug mode, fireqos does not apply the rules, it just prints them.

**Comment by ktsaou** [comment]
merged it

**Comment by ktsaou** [comment]
@philwhineray I think we should release these changes.
They are quite severe for FireQoS.

**Comment by mikenor** [comment]
@ktsaou - 
> hm... I think in debug mode, fireqos does not apply the rules, it just prints them.

Well, that would explain the behaviour I was seeing. But it would also mean that the manual is wrong:
> ## COMMANDS
> ### start; debug
> - Activates traffic shaping on all interfaces, as given in the configuration file.  When invoked as debug, FireQOS also prints all of the tc(8) commands it executes.

**Comment by philwhineray** [comment]
I should have time to do a release Sunday. I'll check the behaviour of debug at the same time and either update the docs or open a separate ticket.

**Pull request merged**
