### PR TITLE
added postprocess2 to execute commands, after firewall activation

### LINKED ISSUE #272: FireHOL fail2ban ipsets issue [help]
I was introduced to FireHOL through the IP Lists site and think it's great so far! Thanks for the hard work! My challenge is that I'm trying to make FireHOL (3.1.1 on Debian Stretch) work in what I think should be a fairly straightforward way but am having a problem actually following the documentation which it seems is not the most up to date. It also doesn't help that ipsets are fairly new to me as well, though very cool.

Essentially I would like to use some of the blacklists (namely firehol_level1 and firehol_level2) in combination with fail2ban for some local blocking of bruteforce attempts. I couldn't actually find documentation on how to apply the firehol_level1 and 2 lists using FireHOL anywhere but I think I got it figured out. I needed to enable each of the lists included inside of those meta-lists idividually with update-ipsets first (is this really right? seems like you should just be able to enable the meta-list and then have it pull the other lists automatically) and then I could modify the firehol.conf file to create the ipsets, to read the netset lists for initial setup, and the blackhole the lists. I've included my config below.

The problem is that the documentation about making fail2ban work seems to be outdated/incorrect for at least some setups. In particular the "postprocess -warn /bin/fail2ban-client reload || return 1" line does not seem to be do anything (though on Debian I have changed it to /usr/bin/fail2ban-client). If I manually run fail2ban-client reload from the command line things seem to work though or if I use the line "postprocess -warn service fail2ban restart || return 1" things seem to work. Unless I've missed it there seems to be no documentation at all about the postprocess command in the FireHOL documentation so I'm unsure of what's going on here and why.

Here's my configuration file which I'm using:
```
version 6

ipv4 ipset create firehol_level1 hash:net
ipv4 ipset addfile firehol_level1 ipsets/firehol_level1.netset
ipv4 ipset create firehol_level2 hash:net
ipv4 ipset addfile firehol_level2 ipsets/firehol_level2.netset

ipv4 blacklist full ipset:firehol_level1 ipset:firehol_level2

interface eth0 internet
        server "http https ssh" accept
        client all accept

postprocess -warn service fail2ban restart || return 1
```

Thanks!

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #272 

```
# firehol try
FireHOL: Saving active firewall to a temporary file...  OK 
FireHOL: Processing file '/etc/firehol/firehol.conf'...  OK  (772 iptables rules)

Your firewall is ready to be fast-activated...
If you don't continue, no changes will have been made to your firewall.
Activate the firewall? (just press enter to confirm or Control-C to stop) : 

FireHOL: Activating ipsets...  OK 
FireHOL: Fast activating new firewall...  OK 
FireHOL: Executing postprocess2 commands...  OK 
Keep the firewall? (type 'commit' to accept - 30 seconds timeout) : commit 

Successfull activation of FireHOL firewall.
FireHOL: Saving activated firewall to '/var/spool/firehol'...  OK 
```

Added this:

```
FireHOL: Executing postprocess2 commands...  OK 
```

### CODE REVIEW

**Comment by ktsaou** [comment]
@philwhineray it complains that `sh is used as a command`. Any ideas how to fix that? I tried to avoid sourcing that file.

**Comment by philwhineray** [comment]
Try $SH_CMD

**Comment by ktsaou** [comment]
thanks! that did the trick

**Comment by bfranske** [comment]
Any word on when this might get merged? Thanks!

**Comment by ktsaou** [comment]
oops! sorry! I forgot it.
Merging it now.

**Pull request merged**
