### PR TITLE
build: actually apply autoconf configuration

### PR DESCRIPTION
**Pull request by alonbl**
firehol cannot work properly if autoconf is not applied, not sure
why there is a complex mechanism to operate without it.

this logic tend to break as nobody actually test the process in
which actual users use this package.

I suggest to remove all these hacks, so developers will run make
after every change in scripts, or alternately generate a
configuration file that is sourced within the scripts instead of
substituting.

in the mean time, this fixes firehol script to apply the
AUTOCONF_RUN correctly within script, please notice that this
method of having .in.in file can also remove the commands.sed
usage as this exactly what autoconf is doing when processing
templates.

the same method should probably apply to other scripts.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

### CODE REVIEW

**Comment by philwhineray** [comment]
Thanks Alon. I will try to look at the patch shortly with a view to merging and extending the logic to the other scripts. Your logic is compelling for me, especially with regards the eating your own dog food aspect.

@ktsaou are you happy for me to pull if it all looks OK? Doing so means the configure step becomes an absolute requirement for running and installation. I think we need it for installation anyway, ever since we split out common functions. As @alonbl points out, forcing developers to do so will probably benefit end-users since the behaviours cannot get out of step.

**Comment by ktsaou** [comment]
OK. Let's do it.

**Comment by philwhineray** [comment]
OK, I would like to merge all the necessary changes in one go, so I have set up branch alonbl-build (name chosen by github!) to work in until all scripts have been converted and the logic is all cleaned up. I'll include any progress updates here or feel free to comment directly in the branch.

**Comment by philwhineray** [comment]
I am about to create a pull request for the alonbl-build tree. I think it is complete and coherent but if anyone has any time to take a look before I dump it on the world, I'd appreciate it. Note that I did a rebase against master so if you had a prior copy you might get conflicts when pulling.

**Comment by ktsaou** [comment]
I noticed that `make clean` does not remove the final program files from `./sbin`, so if you run `./configure` make `make` again the final program files are not updated.

So, `make clean` should remove the program files.

**Comment by ktsaou** [comment]
Also, I think `/usr/lib/firehol` is not the right directory for `functions.common.sh`. It should be `/usr/libexec/firehol`.

**Comment by ktsaou** [comment]
Finally, this setup introduces a big issue: You cannot try a new firehol on a production system before installing it. And after you install it, you actually cannot go back easily.

What I normally do when I install a new version of firehol in a new system is to `make` it and then `./sbin/firehol debug >/tmp/new` which I compare against a `firehol debug >/tmp/old`. If the new generated iptables command are good compared to the old, the firewall is safe.

Now this is lost, since the new firehol may not work with the old `functions.common.sh` and vice versa.

I believe this has to be settled somehow.

I guess we have 2 options:

1. Allow the user to somehow run the new firehol without installing it

or 

2. Force the user to install the new firehol to try it, but come up with an easy way to roll it back to the previous version installed.

Any ideas are welcome.

**Comment by ktsaou** [comment]
I updated all my responses above, so please read them on github.

**Comment by alonbl** [comment]
make clean -> please add CLEANFILES to Makefile.am to clean these.
libexec -> correct, a better location.

option to run a temporary installation may be:

1. use a different prefix for example --prefix=/tmp/firehol
2. allow override of static config for example:
```
FIREHOL_STAT_CONFIG="${FIREHOL_STAT_CONFIG:@FIREHOL_STAT_CONFIG}"
```
Then when run:
```
FIREHOL_STAT_CONFIG=/tmp/xxx /tmp/firehol.new
```

You can have both options, the prefix is safer.

**Comment by philwhineray** [comment]
Well, I read this yesterday and meant to put the package version into the functions path, I just forgot. Then the fallback code would take care of running an uninstalled version - there is just the case where you install, update functions but not version and then run... seems unlikely. How does that sound?

Debian no longer has /usr/libexec and Arch says avoid it too: https://wiki.archlinux.org/index.php/Arch_packaging_standards#Package_etiquette so I think what we have is reasonable, we can try to autodetect the platform if you like, otherwise there should already be a configure option.

**Comment by philwhineray** [comment]
Sorry missed a link, I read this yesterday: https://lwn.net/SubscriberLink/680705/f077c8d92c6cc4dc/ which persuaded me having a version in would be a good idea anyway, to allow multiple installs.

**Comment by alonbl** [comment]
for the libexec, you leave this in autoconf, distro will redirect this
using --libexecdir to wherever they like.

**Comment by ktsaou** [comment]
@philwhineray I like the idea of having multiple versions installed. Then the final program files could be just links to the proper version.

@alonbl I prefer the idea of having an environment variable to point to the proper `libexec`, so that running it without installing it could be accomplished.

So, if we combine both of the above, the program could figure out it is not installed and use its location to find `libexec`.

So what I propose is:

1. Use `/usr/libexec/firehol/3.0.1/` or (in case of unreleased version) `/usr/libexec/firehol/3.0.1-${commit_hash}` as the libraries directory.

2. Set the proper libdir in all programs during `make`.

3. If the libdir does not exist (i.e. program is not installed), attempt to use `$(dirname $0)` for it. The same variable could be set via environment to overwrite.

4. `make install` should install programs like `/usr/sbin/firehol-3.0.1`, rm `/usr/sbin/firehol` and `ln -s /usr/sbin/firehol-3.0.1 /usr/sbin/firehol`. This way the user will have all previously installed versions available.

Using the above, running without installing is possible and multiple versions can be installed so that the user can easily rollback in case the new latest version is not good for him/her.

How does that sound?

**Comment by philwhineray** [comment]
@ktsaou that sounds OK to me in principle. So we have `FIREHOL_LIB_DIR="${FIREHOL_LIB_DIR-PROGRAM_DIR}" fairly early on, then use that for sourcing/whatever? Then if the user sets it, they get a specific directory.

Or should it be a bit more like gcc i.e. the whole main script goes in the versioned directory with just a trivial frontend in the `sbin` dir to exec it? Then users can't accidentally mix and match versions.

**Comment by ktsaou** [comment]
Sorry @philwhineray, I don't get it.

If we do `FIREHOL_LIB_DIR="${FIREHOL_LIB_DIR-$PROGRAM_DIR}"` then how the internal default will work?

I guess we need something like:

```sh
# let the user overwrite, or use the installation default
FIREHOL_LIB_DIR="${FIREHOL_LIB_DIR-@FIREHOL_LIB_DIR@}"

# if it is empty or does not exist, use the program dir
[ -z "${FIREHOL_LIB_DIR}" -o ! -d "${FIREHOL_LIB_DIR}" ] && \
   FIREHOL_LIB_DIR="${PROGRAM_DIR}"
```

Regarding the wrapper or the the link, I think the link is better. Gentoo has done it that way and they have a dedicated program (called `eselect`) to select the default version for each program (it manages the links).

**Comment by philwhineray** [comment]
Yes, my example is bogus, serves me right for trying to write demo code
whilst entertaining a child.

Anyway, I get the general idea so I will try to implement the various
suggestions on the branch and we can pull when it looks ready.

**Comment by philwhineray** [comment]
Quick update. Not made any more progress on this or related #128 yet.

Also, I believe @alonbl ,  @jgmbenoit, @cicku and @SanskritFritz all do packaging. Please feel free to contribute your comments/suggestions as I would like to make everyone's life as easy as possible.

**Pull request closed without merging**
