### PR TITLE
Insert a rawmark mask if none specified

### LINKED ISSUE #256: fireqos - Invalid tc command from rawmark match
If I specify a rawmark match within a class, for example 'match rawmark 3', the tc command fails:

`ERROR:
tc failed with error 1, while executing the command:
/sbin/tc filter add dev eth3-ifb parent 1:0 protocol ip prio 10 u32 match mark 3 flowid 1:11`

From tc:

`Illegal "mark" mask
Illegal "match"`

This is because no mask is specified following the 'mark 3'.

### PR DESCRIPTION
**Pull request by tompickering**
Fixes #256

### CODE REVIEW

**Comment by ktsaou** [comment]
this is a better approach.

I think however it should be something like:

```sh
rawmark|rawmarks)
    local m
    for m in ${2//,/ }
    do
        [[ ! ${m} =~ '/' ]] && m="${m}/0xffffffff"
        mark="${mark} ${m}"
    done
    ;;
```

You see, the whole idea is that you can give multiple marks...

**Comment by tompickering** [comment]
> You see, the whole idea is that you can give multiple marks...

Yep,  I see what you mean! (Sorry, I've only been using fireqos for a few days!). I can't top that approach - branch updated.

**Comment by ktsaou** [comment]
nice. I think it can be merged.
have you tested it?

**Comment by tompickering** [comment]
> have you tested it?

Certainly :) .  Tested with and without a mask, and with a mix of masked and maskless marks.

**Comment by ktsaou** [comment]
merged!
thank you!

**Pull request merged**
