### PR TITLE
fix firehol startup at boot; 

### LINKED ISSUE #260: firehol startup under systemd has to be delayed for conntrack to be initialized
@philwhineray on a debian 8 system I have this problem:

When the system boots, firehol tries to start but it fails, because the conntrack module is not given enough time to initialize itself. My guess is that because systemd starts up everything in parallel, firehol loads the conntrack module, but it fails to be initialized on time.

To overcome this issue, I had to add this:

```
ok=60
while [ $ok -ne 0 ]
do
  	ok=$(( ok - 1 ))
        sysctl -w net/netfilter/nf_conntrack_tcp_loose=0 && ok=0
        [ $ok -ne 0 ] && sleep 1
done
```

So, this waits for the specific sysctl to be available before continuing.

Any ideas if there is a better way to do it?

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #260

### CODE REVIEW

**Comment by philwhineray** [comment]
You will need to use `$SLEEP_CMD` for the build to pass.

Otherwise looks good to me. I take it the file you looked at is similarly delayed? I tried to look in the kernel code but it is a series of tables and funcion pointers where thing depend on each other; I didn't get to the bottom of it.

**Comment by ktsaou** [comment]
> You will need to use $SLEEP_CMD for the build to pass.

yes, I forgot that. I am fixing it now.

> Otherwise looks good to me. I take it the file you looked at is similarly delayed? I tried to look in the kernel code but it is a series of tables and funcion pointers where thing depend on each other; I didn't get to the bottom of it.

I found out that when this loop delays, the directory `/proc/sys/net/netfilter` has only one file in it: `nf_log`. So, I thought to use one of the files that is most likely to stay there for a long time... :1st_place_medal:

**Comment by ktsaou** [comment]
> You will need to use $SLEEP_CMD for the build to pass.

oops! I cannot use `$SLEEP_CMD` at that point. If I put `$SLEEP_CMD` in that file, that command will not be found when the firewall is restored due to the firewall activation of another firewall.

any ideas?

**Comment by ktsaou** [comment]
I can use `read -t 1`, but it is hackish...

**Comment by philwhineray** [comment]
I didn't understand that... did you mean failed activation of another firewall?

**Comment by ktsaou** [comment]
Well, when firehol starts it sources this script. But, if it fails to start, it runs (without sourcing it) a version of that script that was saved at `/var/spool/firehol/firewall_restore_commands.sh`.

So, in the later case, `$SLEEP_CMD` will fail.

The problem is that the script is generated with:

```sh
$CAT_CMD >&20 <<'EOFMTL'
```

note the quotes... no substitution...

**Comment by ktsaou** [comment]
removing the quotes and escaping all `$` will fix that. Doing it now.

**Comment by ktsaou** [comment]
he it is...

**Comment by philwhineray** [comment]
I was about to suggest that, as there isn't too much code. I think it's best since it means the user/distro chosen path will be used and we don't rely on PATH being set up.

**Comment by ktsaou** [comment]
tested it.
It seems good.

@andvgal can you test it?
I have also supplied a `firehol.service` that should start firehol before network.

**Comment by ktsaou** [comment]
btw, @philwhineray on your embedded devices, does `read -t 0.5` work?

**Comment by philwhineray** [comment]
Sadly, no:

~~~~
root@border:~# read -t 0.5
-ash: read: invalid timeout
~~~~

I think it is a busybox limitation.

**Pull request merged**
