### PR TITLE
firehol: set default autosave6 for gentoo/debian

### PR DESCRIPTION
**Pull request by alonbl**

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks Alon!

@philwhineray I think you have done something for deciding autosave locations at package preparation. I don't know if this patch is conflicting with your changes.

Your call...

**Comment by alonbl** [comment]
nothing is using @FIREHOL_AUTOSAVE6@ autoconf variable.

the entire autoconf detection can be removed if not used, or we need to fix the entire build.

**Comment by philwhineray** [comment]
Could you both take a look at #82 

It reworks the command detection to make it more general and also pushes the AUTOSAVE setups back into `./configure` where they can be controlled by distributions.

@ktsaou I don't want to change the way commands are detected without you having a chance for input but I think this new way is better - it allows packagers to set locations at ./configure time, users to override with `firehol-defaults.conf` and finally fallback to runtime detection if the script is used unconfigured.

@alonbl if the move to ./configure will work for you I would sooner go in that direction than runtime detection

**Comment by alonbl** [comment]
I prefer configuration time detection. This patch only provides consistent method with current master.

#82 is nice, but will take a while to get in.

BTW: I usually prefer to minimize template usage in these cases. In this specific case to have a stub file of firehol which is a template and execute the firehol script within a context, instead making the entire firehol script a template.

Anyway, must fix it for our Gentoo users.

**Comment by ktsaou** [comment]
@philwhineray I didn't realize you are waiting for me.
I thought you are planning more changes to be merged together with it.
I am ok. Merge it...

**Comment by philwhineray** [comment]
@ktsaou well there was no rush... I will merge it now.

@alonbl I'm not sure what you mean by current master? Does a merge of #82 solve your issue or do you need the runtime detection anyway?

**Comment by alonbl** [comment]
@philwhineray  yes it works, however I think we need --enable-ipv6 switch, as no that this is build time we need to build this with or without support of ipv6, sequence: user has no ipv6 utilities and builds and install firehol, user adds ipv6 utilities, firehol cannot use these utilities, must be built again with ipv6 support. the solution of that in Gentoo language is USE flags, a machine without ipv6 will trigger --disable-ipv6 while when adding ipv6 it will pull all utilities and such and will trigger --enable-ipv6. when --disable-ipv6 expected behaviour is not to enable ipv6 support, or fail if there are missing dependencies.

**Comment by philwhineray** [comment]
I added `--disable-ipv6` and `--disable-ipv4` options to the configure script and made firehol honour them. The configure does not yet stop checking for e.g. `ip6tables`, however. I will do that next; there is now a selection of options that should be catered for.

**Comment by alonbl** [comment]
Thanks!!! waiting for your next step :)

**Comment by philwhineray** [comment]
OK, it's done. Check it out at your leisure.

**Comment by alonbl** [comment]
Hi,
Thanks!
PAGER is a standard variable name which can be relative, autoconf accept it as is, while the firehol script assume it is full path and complains.

**Comment by alonbl** [comment]
hmm... master does not work for me...

```
udp: option "--destination-port" can only be used once.
Offending line:
-A out_inet1 -p udp --dport 500 -m multiport --source-ports 500,32768:61000,4500 --dport 4500 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
```

something to do with ipsecnat but I do not have it enabled.

**Comment by alonbl** [comment]
please consider to locate bash as mandatory dependency as firehol cannot work without it.

you can also consider using standard SHELL variable of autoconf instead of:
```
AX_CHECK_PROG([SH], [sh], [])
AX_CHECK_PROG([SH], [bash], [])
AX_NEED_PROG([SH], [ksh], [])
```

**Comment by alonbl** [comment]
Hi,

I see also sed of NONE for FIREHOL_CONFIG_DIR, IPRANGE in configure.ac, this is not the right method to accomplish this.

I recommend of using firehol.var.in.in, making firehol script free of autoconf vars, source firehol.vars when executing, if you install both at $libdirexec/ and symlink firehol to /usr/sbin, then you can readlink and source by dirname $0.

in autoconf you process firehol.vars.in.in -> firehold.vars.in and in autimake you sed firehol.vars.in -> firehol.vars with install time settings, for example:
```
SUFFIXES = .in
.in:
        if sed \
                -e 's#[@]prefix_POST@#$(prefix)#g' \
                -e 's#[@]bindir_POST@#$(bindir)#g' \
                $< > $@.tmp; then \
                mv "$@.tmp" "$@"; \
        else \
                rm -f "$@.tmp"; \
                false; \
        fi

libexec_DATA = firehol.vars
```

**Comment by alonbl** [comment]
can we split the iprange utility into separate utility/repo/project it seems not directly related to firehol, while has generic name and installed at sbin.

**Comment by ktsaou** [comment]
Alon thanks for your suggestions. @philwhineray will handle the autoconf stuff.

Regarding this:

> can we split the iprange utility into separate utility/repo/project it seems not directly related to firehol, while has generic name and installed at sbin.

I don't think it should be splitted. `iprange` although is a generic tool (it does not depend on anything else), is used by firehol to [optimize hash:net ipsets](https://github.com/firehol/firehol/wiki/iprange:-optimizing-ipsets-for-iptables) and is also required by `update-ipsets` (actually `update-ipsets` is a front-end to `iprange`). Of course, if it has to be placed in a different place in the source tree, or installed in a different way, @philwhineray will take care of it.

Thanks!

**Comment by alonbl** [comment]
I created iprange as separate package, available here[1]
It also has some cleanups.
I think that best to leave firehol pure shell package.
Your call.

[1] https://github.com/alonbl/iprange

**Comment by ktsaou** [comment]
Alon, explain these to me:

1. `update-ipsets` will not work without iprange
2. `firehol` will have a dependency on iprange

How this will work?

Probably, `update-ipsets` will have to be splitted too. It has no direct relation to firehol.

If we do this and split `iprange` and `update-ipsets` what will the distros do? They will be required to pull these packages too, together with `firehol`.

So, what is the benefit of splitting?

**Comment by ktsaou** [comment]
nice cleanup though! Thanks!

**Comment by alonbl** [comment]
Well, one might ask the same question regarding iptables or any other utility that is being used by firehol.
The configure script should locate all dependencies, iprange is same as any.
If you found it useful enough to be use and imported to your code base, maybe other people will find it useful as well, splitting it into separate package will support that.
Also, packaging it separately enables managing life cycle easier, package it downstream easier.
For example, for rpm based system firehol can be packages as noarch single package, however, adding arch specific tool forces packaging per any supported platform.
You may also find some other improvments/cleanups I added that are specific to this tool, very difficult to manage build options of a specific tool into the umbrella of firehol script as they are not really related in term of customization.

**Comment by ktsaou** [comment]
ok. Based on your response I understand that the biggest problem is the architecture dependency which is introduced with iprange. It is not its relation with firehol but the fact that with it in firehol, the noarch style of the package is lost.

So, your suggestion is `update-ipsets` to remain in the firehol package, but iprange to be splitted. Am I right?

If the new package that will have to be pulled together with firehol will not be a problem for the distributions, I don't see any issue, and I agree to split it.

If however, we may end up with firehol v3 installed without iprange, I am strongly against it.

**Comment by alonbl** [comment]
> So, your suggestion is update-ipsets to remain in the firehol package, but iprange to be splitted. Am I right?

correct.

> If however, we may end up with firehol v3 installed without iprange, I am strongly against it.

it is up to firehol to seek iprange as optional or mandatory, it is your call. if you like it to be mandatory dependency it will behave same as now.

currently it is optional dependency see --disable-iprange.

if you agree the split, can you please review my changes? 1st commit is the source within firehol on your behalf, then my cleanups. when all ok, you can push it to firehol/iprange.

**Comment by ktsaou** [comment]
It is ok. I have review it.

The option `--disable-iprange` has to be removed. `update-ipsets` cannot work without it.

But, please wait for @philwhineray to agree too.

Thanks!

**Comment by alonbl** [comment]
I just added rpm packaging to iprange package.

**Comment by philwhineray** [comment]
I agree the iprange split is a good idea. The `--disable-iprange` does not really do the right thing; it stops the tool from being installed but then adds a check to find it on the system and won't run without it.

@alonbl thanks for all the other autoconf tips - I will start to sort them out when I have a little bit of time.

**Comment by alonbl** [comment]
@philwhineray thanks for forking iprange into firehol, however, using fork is not the best method to do that as my repo remains the master.
you should create a new repo at firehol, clone my repo locally and push to the new repo, this way I can fork my repo from firehol and process will be correct.

**Comment by philwhineray** [comment]
OK done. Also, you should have commit access to the firehol/iprange repo.

**Comment by alonbl** [comment]
> OK done. Also, you should have commit access to the firehol/iprange repo.

thanks! could not fix that using these permissions :)
we are all set now.

**Comment by ktsaou** [comment]
@philwhineray this split means that every time we release firehol we will also have to release iprange (if it has changed).

Currently, `firehol`, `update-ipsets` and `iprange` development are in sync. For example, `update-ipsets` will not work with an `iprange` a few commits back.

So, please keep this in mind.

**Comment by alonbl** [comment]
@ktsaou I was hoping that iprange will change less than the utilities that use it :)

advantage is that it can be fixed and released without releasing firehol and vice versa.

**Comment by philwhineray** [comment]
I just pushed a version option to iprange - I intend to add version detection to the firehol configure script so it can detect a too-old version.

**Comment by ktsaou** [comment]
> @ktsaou I was hoping that iprange will change less than the utilities that use it :)

Yes, this will eventually happen. But, in the meantime, as for example `update-ipsets` is being developed, a few features fit better in `iprange`, so it end up being dependant on specific versions of it.

**Comment by ktsaou** [comment]
by the way, guys I really need some help to migrate also https://github.com/firehol/netdata to autoconf. Do you want me to start an issue about it in its repo?

**Comment by alonbl** [comment]
> by the way, guys I really need some help to migrate also https://github.com/firehol/netdata to autoconf. Do you want me to start an issue about it in its repo?

I can try to do this.

**Comment by ktsaou** [comment]
> I can try to do this.

Great!

**Comment by philwhineray** [comment]
OK, the split is complete - firehol master now looks for iprange externally and checks for the version.

@ktsaou if you make an incompatible change the best thing is to update the version at the top of its `configure.ac` and then update the required version at the top of the firehol `configure.ac`.

I haven't tried to verify the version at runtime although I guess that would not be too hard.

**Comment by alonbl** [comment]
please make sure that this works in cross compile, in which you cannot run a program, instead if cross compiling have a variable to replace version detection.

**Comment by philwhineray** [comment]
I see exactly what you are getting at but sadly have no experience with that - could you possibly do the honours?

**Comment by alonbl** [comment]
```
AC_ARG_VAR([IPRANGE_VERSION], [Version of iprage])
if test "${cross_compiling}" == 'yes'; then
    test -z "${IPRANGE_VERSION}" && AC_MSG_ERROR([IPRANGE_VERSION must be set for cross compile])
else
    IPRANGE_VERSION=`${IPRANGE} --version`
fi
# parse and check IPRANGE_VERSION

**Comment by philwhineray** [comment]
So to be clear - there is not some mechanism for the caller to specify the version they have, we just make the assumption, right?

**Comment by alonbl** [comment]
>So to be clear - there is not some mechanism for the caller to specify the version they have, we just make the assumption, right?

when we are executed in cross compile environment we must be fed the information we cannot collect.

**Comment by philwhineray** [comment]
OK, I misunderstood the AC_ARG_VAR - I have pushed a suitable change at commit 8c415f2435f37623a7cf7260703ddc78ce3eb7d8

**Comment by ktsaou** [comment]
Is this to be merged?

**Comment by alonbl** [comment]
I have no issues in Gentoo and master.

**Pull request closed without merging**
