### PR TITLE
Specify a mask when matching by rawmark

### LINKED ISSUE #256: fireqos - Invalid tc command from rawmark match
If I specify a rawmark match within a class, for example 'match rawmark 3', the tc command fails:

`ERROR:
tc failed with error 1, while executing the command:
/sbin/tc filter add dev eth3-ifb parent 1:0 protocol ip prio 10 u32 match mark 3 flowid 1:11`

From tc:

`Illegal "mark" mask
Illegal "match"`

This is because no mask is specified following the 'mark 3'.

### PR DESCRIPTION
**Pull request by tompickering**
Ensure that the tc command features a mask when matching with rawmark

Fixes #256

### CODE REVIEW

**Comment by ktsaou** [comment]
Thanks!
I think this should also be applied to firehol.
@philwhineray what do you think?

**Comment by ktsaou** [comment]
Now that I think of it again, I am not sure if we should enforce a mask to `rawmark`.

The idea is that `rawmark` should allow us to specify arbitrary masks. Otherwise, firehol and fireqos will not provide any way for the user to specify a custom mask (the only way would be to define a new mark which will complicate things).

So, I think the right solution is to just supply a mask to the fireqos rule that you need to use `rawmark`.

**Comment by tompickering** [comment]
Thanks for the feedback! It would certainly be ideal if users could specify their own mask. My feeling is that as `rawmark` doesn't currently expect a second argument, these should be treated as two separate issues (one bug fix and one feature implementation), however in either case I'll look into a more suitable patch later this evening.

**Comment by ktsaou** [comment]
> My feeling is that as rawmark doesn't currently expect a second argument,

I think it supports `mark/mask`. Doesn't it?

**Comment by tompickering** [comment]
> I think it supports mark/mask. Doesn't it?

Quite right! I do apologise - I wasn't aware of that syntax, otherwise I probably wouldn't have raised the issue at all. I've raised merge request #258 which simply fills in a default mask if none is provided, however feel free to close it off if you'd rather retain current behaviour :) .

**Pull request closed without merging**
