### PR TITLE
hashing filters 

### PR DESCRIPTION
**Pull request by unki**
Hi,

This patch is a first draft of adding tc hashing filters to FireQOS.

Hashing filters can be used to reduce CPU load on classifying every single packet against a bigger tc ruleset.

For example you may have a lot of subnet's in your company network. Let's say:

```
192.168.1.0/24 ..... siteA
192.168.2.0/24 ....  siteB
....
192.168.157.0/24 ... siteC
....
192.168.255.0/24 ... siteD
```

Accordingly an FireQOS configuration can look like this:

```
    class group mycompany commit 512kbit hashfilter src 192.168.0.0/16 0.0.255.0
        class siteA commit 64kbit hashfilter key 1
            match dscp EF
        class siteB commit 64kbit hashfilter key 2
            match dscp EF
        ....
        class siteC commit 64kbit hashfilter key 157
            match dscp EF
        ....
        class siteD commit 64kbit hashfilter key 255
            match dscp EF

    class group end
```

- first FireQOS will install a new hashtable (major-id and divisor currently hardcoded)

```
/sbin/tc filter add dev eth0-ifb parent 1:0 protocol all prio 2 handle 10: u32 divisor 256
```

  The divisor 256 tells tc to create a hashtable with space for 256 entries

- another tc-filter captures all packets from the built-in root hashtable (800::) and matches the source address of those packets against the configured prefix 192.168.0.0/16 and forwards packets to our hashtable (10:)

```
/sbin/tc filter add dev eth0-ifb parent 1:0 protocol all prio 2 u32 ht 800:: match ip src 192.168.0.0/255.255.0.0 hashkey mask 0x0000ff00 at 12 link 10:
```

  in addition - on all successfully matched packets - configured mask 0.0.255.0 will be applied.
  a packet with the address 192.168.157.52 will result in 0.0.157.0.
  this masked value 0.0.157.0 will be used internally to lookup a matching entry on the hashtable.

  To illustrate we can imaging that our hashtable now looks like

```
  |-----------------|
  | hashtable 10:   |
  |-----------------|
  |  10:1           |
  |  10:2           |
  |  ...            |
  |  10:9D (=157)   |
  |  10:FF (=255)   |
  |-----------------|
```

The masked value 0.0.157.0 indicates that tc has to continue on the hashtable entry 10:9D (9D = 157 = our third octet of the subnet network 192.168.157.0).

- On this hashtable entries now further filter get bound that redirect packets from the selected hashtable entry to the tc class. Also all the further matches for protocols, ports, etc. happen here. In our example it's a DSCP match  

```
/sbin/tc filter add dev eth0-ifb parent 1:0 protocol ip prio 10 u32 ht 10:1 match ip tos 0xB8 0xB8 flowid 1:12
 /sbin/tc filter add dev eth0-ifb parent 1:0 protocol ip prio 20 u32 ht 10:2 match ip tos 0xB8 0xB8 flowid 1:13
...
 /sbin/tc filter add dev eth0-ifb parent 1:0 protocol ip prio 30 u32 ht 10:9d match ip tos 0xB8 0xB8 flowid 1:14
...
 /sbin/tc filter add dev eth0-ifb parent 1:0 protocol ip prio 40 u32 ht 10:ff match ip tos 0xB8 0xB8 flowid 1:15
```

Without hashing, at least 256 filter rules would be installed matching from 192.168.0.0/24 to 192.168.255.0/24.
A packet from 192.168.255.3 would first have to be matched against 255 filters from 192.168.0.0/24 to 192.168.254.0/24 before it reaches the right filter 192.168.255.0/24.

With hashing filters it's more like a phonebook lookup.
The identifier is masked out of the address and used to lookup a matching entry in the hashtable.
Immediately, without a lot of CPU effort, more specific matches can start from here.

I hope I was able to explain the concept a bit :-)

### CODE REVIEW

**Comment by ktsaou** [comment]
@unki I merged your last pull requests and now it gives conflicts. Please resolve them.

Nice work! I didn't know such functionality existed.

I have a few suggestions:

As I see it, there could be multiple hashtables per interface. For example one hashfilter classifies traffic from 192.168.0.0/16, another from 10.0.0.0/16.

If the hashfilters are not nested, the changes to accomplish this seem very simple:

    a. use a dynamic handle instead of `10:`.
    b. use the keyword `hashtable` to define a new hashtable at a class, use the keyword `hashfilter` to define that the class participates in the hashtable of another.
    c. use a `name` in `hashtable` and `hashfilter` to allow matching them.

So, to be more generic, we could have something like this:

```bash
class group mycompany commit 512kbit hashtable name1 src 192.168.0.0/16 0.0.255.0
        class siteA commit 64kbit hashfilter name1 0.0.1.0
            match dscp EF
        class siteB commit 64kbit hashfilter name1 0.0.2.0
            match dscp EF
        ....
        class siteC commit 64kbit hashfilter name1 0.0.157.0
            match dscp EF
        ....
        class siteD commit 64kbit hashfilter name1 0.0.255.0
            match dscp EF

    class group end
```

Also, the size of the hashtable can be calculated from the mask. It is `1 << the number of bits set`. In firehol there is the function:

```bash
numberofbits() {
	local x="${1}"

	x=$[ x - ( (x >> 1) & 0x55555555) ]
	x=$[ (x & 0x33333333) + ( (x >> 2) & 0x33333333) ]
	x=$[ (x + (x >> 4) ) & 0x0F0F0F0F ]
	x=$[ x + (x >> 8) ]
	x=$[ x + (x >> 16) ]
	echo $[ x & 0x0000003F ]
}
```

You can adapt this to return the hashtable size, like this:

```bash
mask2bits() {
        local x="${1}"

        x=$[ x - ( (x >> 1) & 0x55555555) ]
        x=$[ (x & 0x33333333) + ( (x >> 2) & 0x33333333) ]
        x=$[ (x + (x >> 4) ) & 0x0F0F0F0F ]
        x=$[ x + (x >> 8) ]
        x=$[ x + (x >> 16) ]
        echo $[ 1 << (x & 0x0000003F) ]
}
```

It will return the hashtable size, given the mask in decimal or hex (prefix hex values with `0x`). For example:

```
# mask2bits 0x0000ff00
256
```

I also suggest to replace the `cidr_length_to_mask()` of last pull request (which I already merged before looking too close) with this:

```bash
cidr_length_to_mask() {
        local n="${1}" hex

        # find the mask in hex
        hex="$(printf "%x" $[ ~(( 1 << ( 32 - n )) -1 ) ])"

        # get the last 8 digits of the number (bash uses 64 bit numbers)
        hex="${hex: -8}"

        printf "%d.%d.%d.%d\n" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}" "0x${hex:6:2}"
}
```

**Comment by ktsaou** [comment]
Oh! I forgot. For each variable in a function, the first time it is assigned, use the `local` keyword. Otherwise, it is a global variable and may interfere with other functions.

**Comment by ktsaou** [comment]
I have made a few more comments, so please it my comments on github, not the email.
Thanks!

**Comment by ktsaou** [comment]
@unki I have merged it. Could you please test it works?

I have not re-structured to be more generic. I just replaced your `cidr_length_to_mask()` and added `mask2bits()`.

Thanks!

**Comment by unki** [comment]
@ktsaou sorry for the late response.

thanks for merging. I will give it a go on one of our major routers.

**Pull request merged**
