### PR TITLE
Strip out NONE from sit0NONE in the wizard/helpme

### PR DESCRIPTION
**Pull request by sndrr**
When running the wizard or helpme I only got eth0 as interface, but I had more interfaces. So I went the FOSS way, and fixed it in the source.

### CODE REVIEW

**Comment by ktsaou** [comment]
Hi,

I guess what you need is not that `tr` command. Check this example:

```sh
$ echo "WELCOME@NONE" | tr "@NONE" " "
W LC M
```

Can you post an `ip link show` to help me see the problem?

**Comment by sndrr** [comment]
This is on a raspberry pi, running raspbian.

```bash
user@host:~# sudo ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether b8:27:eb:1b:c3:a5 brd ff:ff:ff:ff:ff:ff
3: sit0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/sit 0.0.0.0 brd 0.0.0.0
4: sixxs@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1280 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/sit 0.0.0.0 peer 192.87.102.107
18: tun0@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT qlen 100
    link/none 
```

**Comment by sndrr** [comment]
Updated the pull request, so that it now fixes the problem at hand.

**Comment by ktsaou** [comment]
ok, I see now.

FireHOL already has this function for lowercase `@none`:

```sh
${SED_CMD} "s/@[a-z0-9]*//"
```

It should become:

```sh
${SED_CMD} "s/@[A-Za-z0-9]*//"
```

and it will work for both lowercase and uppercase.

Could you please update it for me to pull it?

Thanks for pointing this out!

**Comment by sndrr** [comment]
> Could you please update it for me to pull it?

@ktsaou Fixed now.

**Comment by ktsaou** [comment]
Perfect! Thanks!

(I wanted you to be present on the commit log of FireHOL, I hope you also wanted it!)

**Comment by sndrr** [comment]
:+1:

**Pull request merged**
