### PR TITLE
Make command detection table-driven

### LINKED ISSUE #71: autoconf enable/with have no effect
Hi,

As far as I can see there is an attempt to use autoconf to define default for these:
```
  --with-autosave[[[=PATH]]]
  --with-autosave6[[[=PATH]]]
```

However, I cannot see where it is used, in sbin/firehol there is:
```
# Where /etc/init.d/iptables expects its configuration?
# Leave it empty for automatic detection
test -z "$FIREHOL_AUTOSAVE" && \
        FIREHOL_AUTOSAVE=

# Where /etc/init.d/ip6tables expects its configuration?
# Leave it empty for automatic detection
test -z "$FIREHOL_AUTOSAVE6" && \
        FIREHOL_AUTOSAVE6=
```

I guess it should be  @FIREHOL_AUTOSAVE@ and  @FIREHOL_AUTOSAVE6@ as detection and setting performed by autoconf.

I am unsure what the intention was, I just do not see these been used anywhere and I do want package customization for users.

Thanks!

### PR DESCRIPTION
**Pull request by philwhineray**
If a command is specified in `/etc/firehol/firehol-defaults.conf` it will be used. Otherwise, if the script has been configured with `./configure` the detected versions will be used. If the script has not been configured then the list of possible commands is autodetected.

Resolves #71

### CODE REVIEW

**Comment by ktsaou** [comment]
@philwhineray seems nice! merge it.

**Comment by ktsaou** [comment]
@philwhineray I just made a little patch to fix two issues I found.

There is still an issue: autoconf sets IPRANGE_CMD to /usr/local/sbin/iprange no matter where the `--prefix=` is set.

Can you check it?

**Comment by philwhineray** [comment]
I think the first part of the fix introduces a problem - the arguments are
meant to be passed, in this way it is possible to substitute e.g. `gzip -c
-d` for zcat.

The second part I agree fully.

I will look into the iprange problem and fix it soon.

**Comment by ktsaou** [comment]
> I think the first part of the fix introduces a problem - the arguments are
> meant to be passed, in this way it is possible to substitute e.g. `gzip -c
> -d` for zcat.

I don't know. If we use them like this, then:

1. we should remember never to do `"${X_CMD}"` (enclosed in quotes). They will under conditions fail (which is very bad, it will not fail on us but on users).

2. we should never do `[ -x "${X_CMD}" ]`, so we can never know if the command is there or not.

It is probably better to have:

```sh
zcat() {
   if [ ! -z "${ZCAT_CMD}" -a -x "${ZCAT_CMD}" ]
   then
     "${ZCAT_CMD}" "${@}"
   else
     "${GZIP_CMD}" -dc "${@}"
   fi
```

What do you think?

**Comment by philwhineray** [comment]
> we should remember never to do "${X_CMD}" (enclosed in quotes). They will under conditions fail (which is very bad, it will not fail on us but on users).

True. I think an automatic check (a simple grep in a pre-commit
script, say) to make sure we haven't made this error is preferrable to
setting up special functions, though.

Add zcat() and use two detected variables and there are now 3 or more
ways that a decompression to stdout could be written. All will work
most of the time but fail on unusual systems: all it takes is for
someone to forget to use the special zcat() and the more such commands
the greater the chances of an accident.

A single variable name is simple and consistent, notwithstanding it
must not be enclosed in quotes.

> we should never do [ -x "${X_CMD}" ], so we can never know if the command is there or not.

The point of the detection code (even before these changes) was to
ensure there is always a runnable command or the variable is empty.
Except the special case you just added this should already have been
the case.

Or we could have $ZCAT_CMD and $ZCAT_OPTS be setup but of course this
is another thing that could be used wrong.

**Comment by philwhineray** [comment]
I have pushed a change for the iprange problem.

Looking at the docs it seems that I should really be handling this in
the makefile rather than trying to do so in the configure script. This
will take a bit of effort to re-engineer, so the current fix should
suffice until then.

**Comment by ktsaou** [comment]
What will happen if I uninstall zcat at some point?

You are right that there is no "one size fits all". So we have to choose.

My 2 cents go to any solution that will allow the admin to always know the problem upfront. I don't like running a firewall with missing commands, under any circumstances. If we accept running firehol with missing commands, we can drop the whole idea of external commands management... It is actually the same... We will just assume that the package manager will guarantee the needed commands are installed (of course the distro maintainers will have to know what is needed - so moving everything at the makefile should be sufficient).

Your call Phil.
Give the solution you see fit...

**Comment by philwhineray** [comment]
> What will happen if I uninstall zcat at some point?

I think with the second part of your patch they will get an error.
This just needs a tweak so that it understands there may be optional
arguments.

> You are right that there is no "one size fits all". So we have to choose.
>
> My 2 cents go to any solution that will allow the admin to always know the problem upfront. I don't like running a firewall with missing commands, under any circumstances. If we accept running firehol with missing commands, we can drop the whole idea of external commands management... It is actually the same... We will just assume that the package manager will guarantee the needed commands are installed (of course the distro maintainers will have to know what is needed - so moving everything at the makefile should be sufficient).

I think I understand your concerns. As you guessed, I like my
solution... I will update the code to ensure that firehol aborts early
if a command is missing.

I will also find a way to ensure we don't include quotes around
commands by accident. Do you use the git pre-commit script from the
packaging dir? I will most likely update that to do it.

> Give the solution you see fit...

Hopefully I can satisfy us both. If I cannot achieve the above or
there are problems in practice I will change it back.

**Comment by ktsaou** [comment]
> Do you use the git pre-commit script from the
> packaging dir? I will most likely update that to do it.

I am not sure... so most probably not...
Please help me...

**Comment by philwhineray** [comment]
> > Do you use the git pre-commit script from the
> > packaging dir? I will most likely update that to do it.
> 
> I am not sure... so most probably not...

All you have to do (in your local firehol repo) is:

`cp packaging/pre-commit .git/hooks/`

git will run the script before it allows a `git commit` to proceed.

As you are not on debian/ubuntu you will get a warning message
about dpkg-gencontrol but this will not stop the process running.

dpkg-gencontrol is checking the format of the ChangeLog file. If
the warning bothers you we can suppress it.

**Comment by philwhineray** [comment]
I did one part - every detected command is now checked to exist and if it is required execution stops with a message to indicate the fix.

I found a couple of undetected commands so will fix those at some point and try to handle the case of missing `which` also.

Those will work whether we allow detecting with options or use function wrappers. That just leaves verifying the commands are always used without quotes and tested for with -z not -x. There are a couple of unusual cases but I don't think it will be too hard to add to the pre-commit checks.

**Comment by ktsaou** [comment]
@philwhineray I think this:

```sh
local cmd=$(echo $val | cut -f1 -d' ')
```

can become this:

```sh
local cmd=${val/ */}
```

The first is too slow (two forks for each command to be checked).
The same can be also be used directly with

```sh
 [ ! -z "${X_CMD}" -a -x "${X_CMD/ */}" ] && echo "OK"
```

**Comment by ktsaou** [comment]
Hm.. you can also use an array:

```sh
# x="1 2 3"
# y=($x)
# echo ${y[0]}
1
```

**Comment by philwhineray** [comment]
OK I will sort it when I have a bit of time. Maybe tonight.

**Comment by philwhineray** [comment]
OK I made the change

Also, I updated the pre-commit to check for commands in quotes. To try
it, copy the new pre-commit to .git/hooks and it should abort commits
before you are asked for a message.

If this seems passable to you I will put back the ${@} so the options
are included again.

**Comment by ktsaou** [comment]
Nice.
I think it is ok now.

Phil do you plan to make these changes to the other tools too?

**Comment by philwhineray** [comment]
I think it makes sense if you are OK with it.

First I will need to normalise the variable names - do you prefer uppercase
like FireHOL or lowercase like FireQOS?

Then maybe these common routines are a good candidate for extraction to
/usr/lib to check the way such things will work in future.

**Comment by ktsaou** [comment]
I agree.

I suggest upper case because they will be easily distinguishable from normal commands (i.e. you can easily mess `sed` and `sed_cmd`, while `SED_CMD` stands out)

**Pull request merged**
