### PR TITLE
add docker_bridge helper; support newer iptables versions

### LINKED ISSUE #264: firehol not starting on most major distributions
I am not able to start firehol from the latest pull on Ubuntu16, Centos6, RHEL7.

```
# firehol try
 WARNING: error initializing iptables: IPv4 disabled
 WARNING: error initializing ip6tables: IPv6 disabled
 ERROR: Neither IPv4 nor IPv6 is available - exiting

```

Debian 8 is still working. 

The problem seams to be the following arguments on iptables commands:

```
+ /sbin/iptables **-wnxvL**
+ '[' 2 -ne 0 ']'
+ echo ' WARNING: error initializing iptables: IPv4 disabled'
 WARNING: error initializing iptables: IPv4 disabled
```

```
iptables -wnxvL
iptables v1.4.21: wait seconds not numeric
Try `iptables -h' or 'iptables --help' for more information.
```

Correcting the above to the following seams to work.

`iptables -w 1 -nxvL`

### PR DESCRIPTION
**Pull request by ktsaou**
#114 

This PR adds a new helper, named `docker_bridge`.

It is used like this:

```
docker_bridge INTERFACE SUBNET
```

where `INTERFACE` is usually `docker0` and `SUBNET` is `172.17.0.0/16`.

The helper will setup the basic functionality docker requires:

1. setup `nat/DOCKER`, `filter/DOCKER`, `filter/DOCKER-USER`, `filter/DOCKER-ISOLATION` chains
2. provide static defaults for all these chains
3. allow the host to reach the containers
4. allow the containers to use the internet
5. allow the containers to talk to each other

> The helper **does not** setup any port mappings, and **does not** add any useful rules under any of the docker chains. The only way to get these rules after a firewall restart, is to also restart docker.

The helper can safely be called many times to setup multiple docker bridges.

---

allow firehol to work on newer iptables versions

fixes #264

### CODE REVIEW

**Comment by delebru** [comment]
Great addition!! Thanks! :D 

Is this helper included in 3.1.6? Else how can I upgrade my firehol on Centos 7?

Also, what exactly should I be adding to my firehol's config? Let's say I have a container which runs a http server on port 8080 and I want it to be accessible on my host's public IP on port 80. I run my container with `-p 80:8080` but what should firehol's config look like?

```
version6

interface eth0 world
        server http accept
        client http accept

interface docker0 docker
        policy accept

docker_bridge docker0 172.17.0.0/16
        policy accept
```
????

**Comment by alekc** [comment]
For those who ends up here from google. I managed to have this working through following config

```
#Docker Stuff
#https://github.com/firehol/netdata-demo-site/blob/master/files/etc/firehol/firehol.conf
#
containers="docker0,br-8527e3e4e5bb"
docker_bridge docker0 172.17.0.0/16
docker_bridge br-8527e3e4e5bb 172.18.0.0/16

interface "${containers}" container
    policy accept
```

Far from being ideal since the br-8527e3e4e5bb is individual for every machine, but now I am at least able to reach a container from the localhost.

**Comment by alekc** [comment]
Didn't really work for me for some reason. I've opened a separated issue (#360 )

**Comment by rishiloyola** [comment]
@delebru Did you fix your issue? Can you share your config with me? I am facing the same issue.

**Comment by delebru** [comment]
@rishiloyola sorry but I still don’t know how to solve it... We ended up not using docker but I’m still interested to know how to accomplish this.

**Pull request merged**
