### PR TITLE
Moved the 'simple service' definitions into a central place.

### PR DESCRIPTION
**Pull request by wingunder**
Updating the 'simple service' definitions is not optimal, as it is
hard-coded in the firehol and fireqos scripts. This usually requires
an update in two different places.
 
This patch moves the 'simple service' definitions into the
sbin/simple_services.sh file. This requires firehol and fireqos to get
generated, as we probably do not want to add a run-time dependency on
them for including (actually sourcing) sbin/simple_services.sh.
 
In order to keep things easy for development, the firehol.sh and
fireqos.sh programs should be used. They include the external
definitions conditionally, so there's no need to regenerate (make)
firehol and fireqos constantly, while developing. The conditional
include will be skipped in the generated firehol and fireqos scripts.

### CODE REVIEW

**Comment by wingunder** [comment]
The check fails here:
$ git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
fatal: Path 'sbin/firehol' exists on disk, but not in the index.
fatal: Path 'sbin/fireqos' exists on disk, but not in the index.

This is correct, but in this pull request, the 2 missing files are really not in git any more. They get generated. Obviously the ./packaging/check-files script now needs to be carefully massaged for this to work.

Before I go down this road, I would first like to know if the pull request as such is more or less acceptable or not?

Thanks in advance for any hints, feedback, help, etc.

**Comment by ktsaou** [comment]
Hi, yes this would be nice.
Both firehol and fireqos can use the same services.

@philwhineray what do you think?

**Comment by philwhineray** [comment]
Hi @wingunder, thanks for making a PR.

The packaging checks can be updated under `packaging` if necessary. They are quite strict to make sure everything is left out/included by accident.

I actually think the best approach would be to treat your new file identically to `install.config` and `functions.common`. These files are already installed appropriately by the `Makefile.am` and sourced at runtime, so you probably just need to add an entry in the existing locations.

In addition the docs auto-generate in part based on looking at the service entries in the firehol script, so that will need updating and checking if the entries are moved to a new file.

With those modifications the scripts will not need an extra generation step and I'd happy in principle to pull.

**Comment by wingunder** [comment]
Thank you @ktsaou and @philwhineray for the feedback. I really appreciate it.

Ok, it's good to know that I can add a file and make both firehol and fireqos use it, in contrast to my generation hack. I was just concerned of breaking downstream packages (.deb, .rpm, etc), by adding another file. Is there something special that I need to do for the downstream packaging, or does this happen transparently, or is this then up to the downstream maintainers to take care of?

**Comment by ktsaou** [comment]
> Is there something special that I need to do for the downstream packaging, or does this happen transparently, or is this then up to the downstream maintainers to take care of?

I think that if the make files install it, everything will be good.
I am not 100% sure though...

**Comment by wingunder** [comment]
Hi,
It seems as if it's ok now. I however would like to quash my commits before you pull, but let's first see what you think of it.

Possible issues:
- I'm not sure if 'simple_services.sh' is an appropriate name. I won't mind to change it.
- It could be that my changes to the doc/tools/mkservicelinks and doc/tools/mkserviceman are not desired.
- Is the content of the doc-generation checked automatically? I did some random manual checks and it look ok to me.
- Is there any documentation that I need to do for this change?

Thanks in advance for your feedback.

**Comment by philwhineray** [comment]
Hi, good work - the outputs look OK to me. Just one thing: looking at a diff with master there is a set of `fireqos` services that were not in `firehol` which have been removed and maybe forgotten. They look like this in master:

~~~~
# FireQOS only services
server_torrents_ports="tcp/6881:6999 udp/6881:6999"
server_facetime_ports="udp/3478:3497 udp/16384:16387 udp/16393:16402"
server_hangouts_ports="udp/19302:19309 tcp/19305:19309"
server_gtalk_ports="tcp/5222 tcp/5228"
server_teamviewer_ports="tcp/5938"
server_ping_ports="icmp/any"
server_tcp_ports="tcp/any"
server_udp_ports="udp/any"
server_surfing_ports="tcp/0:1023"
~~~~

These are incomplete for `firehol`, and it might not be appropriate to add them anyway. I guess they might be needed for existing `fireqos` users though. @ktsaou will be able to confirm. 

If you want to treat them the same, I suggest that you rename `simple_services.sh` to maybe `common.services` (a `.sh` extension does not add much IMO) and then have an extra `fireqos.services` which is sourced only by `fireqos` and doesn't need any of the documentation updates, just the ones to install it.

**Comment by philwhineray** [comment]
Or `services.common` and `services.firehol` would be more in keeping with `functions.common`...

**Comment by wingunder** [comment]
Thanks for the feedback. Sorry for not diffing in the definitions of firehol and fireqos. My mistake...

Your services.common, services.firehol and services.fireqos solution is a very good idea and I planned to used it, but I ran in to a problem. If I keep the server_, client_ and helper_ definitions grouped, fireqos will get the client_ and helper_ definitions, which it did not have before. Will this be a problem?

If fireqos should _not_ have client_ and helper_ definitions, how about splitting the definitions into:
- services_server.firehol
- services_client.firehol
- services_helper.firehol

and
- services_server.fireqos (fireqos only has server_ definitions)

This might not be so readable at first sight, but things could be bearable with something like:
`# cat services_*.firehol | sort -t_ -f -k2,2 -k1,1 |sed -e 's/^client/\nclient/' | less`

The latter solution is more to my liking, but it's your call.

**Comment by philwhineray** [comment]
Sorry for the slow reply... I don't get a lot of time but I don't mean to leave you hanging.

In my view, if the extra definitions don't interfere with fireqos, then I would just let them be included. The cost of sourcing them is likely negligible and it will make maintenance easier.

**Comment by wingunder** [comment]
No problem, @philwhineray, I also finally found time to look at this again. It should be as agreed now.

I had did not want to rely on manually sorting out and checking the new sbin/service.* files, so I wrote a small shell script that extracts the services from the original sbin/firehol and sbin/fireqos and inserts it into an sqlite3 db. I did not check the script in, as it's just a transitional tool. It might however not be a bad idea to keep the services in a db and then just generate the sbin/service.* files. This could make the maintenance easier in the future.

Anyhow, the script could be found here:
https://gist.github.com/wingunder/3698571b17c91ac722318e6b33e37c92

**Comment by philwhineray** [comment]
Looks good to me.

You said you wanted a chance to squash the result before if gets merged? Go ahead, now is the time.

I'm not convinced that a database makes things easier to maintain because then we have a binary to manage and changes will not shown up in version control. Which is not to say that there isn't a better format for storing the service information, there quite probably is.

**Comment by wingunder** [comment]
Thanks.
The squashed commit is here: ba494063c190fcc85c7c90348ee3eb3f86d4f41b or alternatively, in this pull request: https://github.com/firehol/firehol/pull/313
(Sorry, github doesn't seem to like my way of squashing.)

> I'm not convinced that a database makes things easier to maintain because then we have a binary to manage and changes will not shown up in version control.

Hmm, one could just add the dumped (text version) sqlite3 data to git. But another draw-back would be the added dependency of sqlite3.

> Which is not to say that there isn't a better format for storing the service information, there quite probably is.

Yes, I agree. How about JSON?
I saw that jq is being used in update-ipsets, so we're half way there. Would it be of help if I give this a try in a separate pull request?

**Comment by philwhineray** [comment]
If you want to have a crack at putting all the service info into a JSON format which then generates the rest, I'm OK with that in principle.

It would be nice to add a pre-commit/travis check for ordering and styling of the JSON to help it stay in good shape over time, although obviously that's more than we do at present so I wouldn't block a pull without.

**Pull request closed without merging**
